import random


#Create the Melee Weapons Table
Hand = 1
Short = 2
Medium = 3
Long = 4
VeryLong = 5
ExtremelyLong = 6

HitZones = {
                1 : { "name" : "Lower Legs" }
             }

MeleeWeapons = {           
                6 : { "name" : "Sidesword",
                      "notes" : "DTN is increased by +1 against two-handed and heavy one-handed swords, by +2 against light pole-arms and one-handed mass weapons, and by +3 against heavy pole-arms and two-handed mass weapons."} ,

                7 : { "name" : "Rapier" ,
                      "notes" : "DTN is increased by +1 against daggers and sideswords, by +2 against one-handed swords, by +3 against two-handed and heavy one-handed swords, by +4 against light pole-arms and one-handed mass weapons, and by +5 against heavy pole-arms and two-handed mass weapons. The point will break on any connecting swing against armor better than gambeson or pliable leather unreinforced by metal, reducing Reach to Medium and Thrust DR to 0."} ,

                12 : { "name" : "Wakizashi" ,
                       "description" : "A short sword with a blade of the Katana type." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : -2,
                       "swingAC" : -1,
                       "armorsDR" : -1} ,

                13 : { "name" : "Kopis" ,
                       "description" : "An ancient Greek one-edged short sword with a forward curve and a slight flare to the blade before it tapers to a point." ,
                       "reach" : Short,
                       "sATN" : 7,
                       "sDR" : 1,
                       "tATN" : 6,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : -1,
                       "DefAC" : 1,
                       "tOffAC" : 1} ,

                14 : { "name" : "Gladius" ,
                       "description" : "An ancient Roman short sword with a stiff diamond cross-section and edges either parallel for most of its length before tapering to an acute point, or else of more slightly flaring xiphos-type." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 0,
                       "tATN" : 6,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : -2,
                       "armortDR" : 1} ,

                15 : { "name" : "Spatha" ,
                       "description" : "The ancient Roman version of the arming sword, tapering slightly along most of its length before suddenly tapering to an acute point." ,
                       "reach" : Medium,
                       "sATN" : 7,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : -1,
                       "tOffAC" : 1} ,

                16 : { "name" : "Viking Sword" ,
                       "description" : "The Viking version of the Roman spatha, with a less acute point." ,
                       "reach" : Medium,
                       "sATN" : 7,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : -1} ,

                17 : { "name" : "Dagger" ,
                       "description" : "A straight fighting knife with a substantial blade, usually two-edged." ,
                       "reach" : Hand,
                       "sATN" : 6,
                       "sDR" : -1,
                       "tATN" : 5,
                       "tDR" : 0,
                       "DTN" : 9,
                       "bDR" : -3} ,

                18 : { "name" : "Stiletto" ,
                       "description" : "A dagger with a slender blade of very stiff diamond cross-section, tapering to a very acute point." ,
                       "reach" : Hand,
                       "sATN" : 6,
                       "sDR" : -2,
                       "tATN" : 5,
                       "tDR" : 0,
                       "DTN" : 9,
                       "bDR" : -4,
                       "armortDR" : 1} ,

                19 : { "name" : "Parrying Dagger" ,
                       "description" : "A dagger, usually with a slightly more slender blade, but a very broad and sturdy cross-guard." ,
                       "reach" : Hand,
                       "sATN" : 6,
                       "sDR" : -1,
                       "tATN" : 5,
                       "tDR" : 0,
                       "DTN" : 6,
                       "bDR" : -4,
                       "OffAC" : 1,
                       "notes" : "The DTN is increased by +1 against one-handed swords, by +2 against two-handed and heavy one-handed swords, by +3 against light pole-arms and one-handed mass weapons, and by +4 against heavy pole-arms and two-handed mass weapons."} ,


                20 : { "name" : "Club" ,
                       "description" : "A stout stick, thicker at the business end." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : -1,
                       "DTN" : 9,
                       "bDR" : 1,
                       "shock" : 1} ,

                21 : { "name" : "Mace" ,
                       "description" : "A stout stick with a head bound in metal or wholly made of metal or sometimes stone." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : -1,
                       "DTN" : 9,
                       "bDR" : 1,
                       "shock" : 1,
                       "OffAC" : 1} ,

                22 : { "name" : "Flanged Mace" ,
                       "description" : "A mace with flanges to the sides of the head, optimized to transfer damage through armor." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : -1,
                       "DTN" : 9,
                       "bDR" : 1,
                       "shock" : 1,
                       "OffAC" : 1,
                       "armorsDR" : 1} ,

                23 : { "name" : "Spiked Mace" ,
                       "description" : "A mace with spikes for tearing grisly wounds." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 1,
                       "tATN" : 7,
                       "tDR" : -1,
                       "DTN" : 9,
                       "bDR" : 1,
                       "shock" : 1,
                       "pain" : 1,
                       "BL" : 1,
                       "OffAC" : 1,
                       "armorsDR" : -1} ,

                24 : { "name" : "War-Flail" ,
                       "description" : "A long staff with a much shorter, metal-shod stick with spikes all around affixed to its end by a very short length of chain; wielded with two hands." ,
                       "reach" : VeryLong,
                       "sATN" : 7,
                       "sDR" : 2,
                       "DTN" : 8,
                       "bDR" : 2,
                       "sOffAC" : 1,
                       "shock" : 1,
                       "pain" : 1,
                       "BL" : 1,
                       "parry" : -1} ,

                25 : { "name" : "Hatchet" ,
                       "description" : "An axe with a short haft." ,
                       "reach" : Hand,
                       "sATN" : 6,
                       "sDR" : 0,
                       "DTN" : 8,
                       "bDR" : -1} ,

                26 : { "name" : "Hand-Axe" ,
                       "description" : "A hatchet with a longer haft an slightly larger head." ,
                       "reach" : Short,
                       "sATN" : 7,
                       "sDR" : 1,
                       "DTN" : 9,
                       "bDR" : 0,
                       "armorsDR" : 1} ,

                27 : { "name" : "Long-Hafted Axe, One-Handed" ,
                       "description" : "An axe with a much longer handle and maybe a slightly larger head." ,
                       "reach" : Medium,
                       "sATN" : 7,
                       "sDR" : 1,
                       "DTN" : 9,
                       "bDR" : 0,
                       "armorsDR" : 1,
                       "shock" : 1,
                       "switch" : 1} ,

                27.3 : { "name" : "Long-Hafted Axe, Two-Handed" ,
                         "description" : "An axe with a much longer handle and maybe a slightly larger head." ,
                         "reach" : Medium,
                         "sATN" : 7,
                         "sDR" : 2,
                         "DTN" : 7,
                         "bDR" : 1,
                         "armorsDR" : 1,
                         "shock" : 1,
                         "switch" : 1} ,

                27.6 : { "name" : "Long-Hafted Axe, Two-Handed" ,
                         "description" : "An axe with a much longer handle and maybe a slightly larger head." ,
                         "reach" : Long,
                         "sATN" : 8,
                         "sDR" : 3,
                         "DTN" : 8,
                         "bDR" : 2,
                         "armorsDR" : 1,
                         "shock" : 1,
                         "switch" : 1} ,

                28 : { "name" : "Great Axe" ,
                       "description" : "A long-hafted axe with perhaps a slightly longer haft and a bigger head, to be wielded with both hands." ,
                       "reach" : Medium,
                       "sATN" : 7,
                       "sDR" : 2,
                       "DTN" : 7,
                       "bDR" : 1} ,
                
                28.5 : { "name" : "Great Axe" ,
                         "description" : "A long-hafted axe with perhaps a slightly longer haft and a bigger head, to be wielded with both hands." ,
                         "reach" : Long,
                         "sATN" : 8,
                         "sDR" : 4,
                         "DTN" : 9,
                         "bDR" : 2} ,

                29 : { "name" : "War-Hammer, Hammerhead" ,
                       "description" : "A warhammer with a rather small, but powerful head, often with a beak opposite it." ,
                       "reach" : Short,
                       "sATN" : 6,
                       "sDR" : 1,
                       "tATN" : 8,
                       "tDR" : -1,
                       "DTN" : 9,
                       "bDR" : 1,
                       "switch" : 1,
                       "armorsDR" : 1,
                       "shock" : 1} ,
                
                29.5 : { "name" : "War-Hammer, Beak" ,
                         "description" : "A warhammer with a rather small, but powerful head, often with a beak opposite it." ,
                         "reach" : Short,
                         "sATN" : 7,
                         "sDR" : 1,
                         "tATN" : 8,
                         "tDR" : -1,
                         "DTN" : 9,
                         "bDR" : 1,
                         "switch" : 1,
                         "armorsDR" : 1} ,

                30 : { "name" : "Quarterstaff" ,
                       "description" : "A stout staff, as tall as its wielder or slightly taller." ,
                       "reach" : [Medium, Long],
                       "sATN" : 6,
                       "sDR" : 0,
                       "tATN" : 6,
                       "tDR" : 0,
                       "DTN" : 5,
                       "bDR" : 0,
                       "tOffAC" : 1,
                       "notes" : "Can equally be used at Medium and Long Reach at the same time."} ,

                31 : { "name" : "Short Spear, One-Handed" ,
                       "description" : "A spear, as tall as its wielder or slightly shorter." ,
                       "reach" : Medium,
                       "sATN" : 8,
                       "sDR" : 0,
                       "tATN" : 7,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : 0,
                       "switch" : 1} ,

                31.5 : { "name" : "Short Spear, Two-Handed" ,
                         "description" : "A spear, as tall as its wielder or slightly shorter." ,
                         "reach" : Medium,
                         "sATN" : 0,
                         "sDR" : 0,
                         "tATN" : 6,
                         "tDR" : 1,
                         "DTN" : 6,
                         "bDR" : 0,
                         "switch" : 1} ,

                32 : { "name" : "Long Spear, One-Handed" ,
                       "description" : "A spear, significantly taller than its wielder." ,
                       "reach" : Long,
                       "sATN" : 9,
                       "sDR" : 0,
                       "tATN" : 8,
                       "tDR" : 1,
                       "DTN" : 8,
                       "bDR" : 0,
                       "switch" : 1} ,

                32.5 : { "name" : "Long Spear, Two-Handed" ,
                         "description" : "A spear, significantly taller than its wielder." ,
                         "reach" : [Medium, Long],
                         "sATN" : 0,
                         "sDR" : 0,
                         "tATN" : 6,
                         "tDR" : 1,
                         "DTN" : 6,
                         "bDR" : 0,
                         "switch" : 1} ,

                33 : { "name" : "Halberd, Axe-Blade" ,
                       "description" : "A long spear with an axe-blade and a spike opposite that." ,
                       "reach" : VeryLong,
                       "sATN" : 8,
                       "sDR" : 4,
                       "tATN" : 7,
                       "tDR" : 1,
                       "DTN" : 7,
                       "bDR" : 2,
                       "OffAC" : 1,
                       "DefAC" : 1,
                       "switch" : 1,
                       "armorsDR" : 1} ,

                33.5 : { "name" : "Halberd, Back-Spike" ,
                         "description" : "A long spear with an axe-blade and a spike opposite that." ,
                         "reach" : VeryLong,
                         "sATN" : 8,
                         "sDR" : 4,
                         "tATN" : 7,
                         "tDR" : 1,
                         "DTN" : 7,
                         "bDR" : 0,
                         "OffAC" : 1,
                         "DefAC" : 1,
                         "switch" : 1,
                         "armorsDR" : 1} ,

                34 : { "name" : "Naginata" ,
                       "description" : "A long spear with a long, one-edged, slightly curved blade, used with two hands for mostly slashing attacks." ,
                       "reach" : [Long, VeryLong],
                       "sATN" : 8,
                       "sDR" : 3,
                       "tATN" : 6,
                       "tDR" : 1,
                       "DTN" : 6,
                       "bDR" : 0,
                       "tOffAC" : 1,
                       "armortDR" : -1} ,
                 }

Armors = {
    
                1 : { "name" : "Gambeson" ,
                      "description" : "Pliable textile armor made of a number of layers of quilted cloth and stuffed with cotton, animal hair, or other padding." ,
                      "pAV" : 1,
                      "bAV" : 2,
                      "cAV" : 2} ,

                2 : { "name" : "Leather" ,
                      "description" : "Tough, yet pliable, cured hide." ,
                      "pAV" : 2,
                      "bAV" : 1,
                      "cAV" : 2} ,

                3 : { "name" : "Leather with Metal" ,
                      "description" : "Pliable leather with short metal strips or rings sewn in strategic places to guard against cuts." ,
                      "pAV" : 2,
                      "bAV" : 1,
                      "cAV" : 3} ,

                4 : { "name" : "Hardened Leather" ,
                      "description" : "Cured hide boiled and then dried to make it harder, at the cost of pliability. It can be fashioned into segments large enough to serve as helmets and greaves, but not for workable breastplates." ,
                      "pAV" : 3,
                      "bAV" : 2,
                      "cAV" : 2} ,

                5 : { "name" : "Leather Lamellar" ,
                      "description" : "Strips of leather with holes fashioned into its edges and that are bound together and overlapped by neighboring pieces. Leather Lamellar is quite rigid and cannot be used to protect a joint. Requires wearing a gambeson underneath." ,
                      "pAV" : 3,
                      "bAV" : 3,
                      "cAV" : 3} ,

                6 : { "name" : "Metal Lamellar" ,
                      "description" : "Strips of metal with holes fashioned into its edges and that are bound together and overlapped by neighboring pieces. Leather Lamellar is quite rigid and cannot be used to protect a joint. Requires a gambeson to be worn underneath." ,
                      "pAV" : 4,
                      "bAV" : 4} ,

                7 : { "name" : "Brigandine" ,
                      "description" : "Armor made of palm- to hand-sized metal plates, each sandwiched between two layers of heavy canvas or soft leather and riveted together. Brigandine is quite rigit and cannot be used to protect joints, and requires a gambeson to be worn underneath." ,
                      "pAV" : 4,
                      "bAV" : 4} ,
                
                8 : { "name" : "Mail" ,
                      "description" : "This armor consists of a mesh of small metal rings, each interlinked with neighboring rings. It is supremely pliable and can therefore be used to protect joints, but it too requires a gambeson to be worn underneath" ,
                      "pAV" : 4,
                      "bAV" : 3} ,

                9 : { "name" : "Brigandine over Mail" ,
                      "description" : "" ,
                      "pAV" : 5,
                      "bAV" : 3} ,

                10 : { "name" : "Plate Pieces" ,
                       "description" : "" ,
                       "pAV" : 6,
                       "bAV" : 4} ,

                11 : { "name" : "Articulated Plate" ,
                       "description" : "" ,
                       "pAV" : 7,
                       "bAV" : 5}
                
           }

Shields = {
                1 : { "name" : "Buckler" ,
                      "description" : "" ,
                      "mDTN" : 7,
                      "tDTN" : 8,
                      "pDTN" : 11} ,

                2 : { "name" : "Small Shield" ,
                      "description" : "" ,
                      "mDTN" : 6,
                      "tDTN" : 7,
                      "pDTN" : 9} ,

                3 : { "name" : "Large Shield" ,
                      "description" : "" ,
                      "mDTN" : 5,
                      "tDTN" : 6,
                      "pDTN" : 7}
            }

#Decide what type of game you will be playing. For now there is just Gladiator
GameType = input("What type of game do you want to play? For now there is only Gladiator.\n>")
if GameType == "Gladiator":
    #Create a dictionary of rooms.
    Rooms = {
                1 : { "name" : "the Preparation Room"},

                2 : { "name" : "the Arena"}
              }
    #Set the player in the first room.
    currentRoom = 1
    print("You find yourself in the preparation room beneath the Arena. You hear the roar of the crowd above you.")
    print("o==[=========> <=========]==o")

    #Define Humanoids, the framework for both the player and most enemies.
    class Humanoid:
        def __init__(self, name, brawn, daring, tenacity, heart, sagacity, cunning, reflex, aim, knockdown, knockout, proficiency, weapon, shield, armor, zones):
            self.name = name
            self.brawn = brawn
            self.daring = daring
            self.tenacity = tenacity
            self.heart = heart
            self.sagacity = sagacity
            self.cunning = cunning
            self.reflex = reflex
            self.aim = aim
            self.knockdown = knockdown
            self.knockout = knockout
            self.proficiency = proficiency
            self.weapon = weapon
            self.shield = shield
            self.armor = armor
            self.zone1 = zones

    #Define and create a dictionary of Characters.
#    Character = {
#                0 : { "name" : "Gladiator",
#                      "brawn" : ,
#                      "daring" : ,
#                      "tenacity" : ,
#                      "heart" : ,
#                      "sagacity" : ,
#                      "cunning" : ,
#                      "proficiency" : ,
#                      "weapon" : MeleeWeapons[15],
#                      "shield" : Shields[1]} ,
#                }

    #Define and create a dictionary of Enemies.
    Enemies = {
                0 : { "name" : "Slave Fighter 1",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                1 : { "name" : "Slave Fighter 2",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : 2} ,

                2 : { "name" : "Slave Fighter 3",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                3 : { "name" : "Slave Fighter 4",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                4 : { "name" : "Soldier, Rank-and-file 5",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                5 : { "name" : "Soldier, Rank-and-file 6",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                6 : { "name" : "Soldier, Rank-and-file 7",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                7 : { "name" : "Soldier, Rank-and-file 8",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                8 : { "name" : "Soldier, Rank-and-file 9",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[15],
                      "shield" : Shields[2]} ,

                9 : { "name" : "Soldier, Rank-and-file 10",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[15],
                      "shield" : Shields[2]} ,

                10 : { "name" : "Soldier, Rank-and-file 11",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                11 : { "name" : "Soldier, Rank-and-file 12",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                12 : { "name" : "Soldier, Rank-and-file 13",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                13 : { "name" : "Soldier, Rank-and-file 14",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                14 : { "name" : "Soldier, Rank-and-file 15",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                15 : { "name" : "Soldier, Rank-and-file 16",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                16 : { "name" : "Soldier, Rank-and-file 17",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                17 : { "name" : "Soldier, Rank-and-file 18",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                18 : { "name" : "Soldier, Rank-and-file 19",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                19 : { "name" : "Soldier, Rank-and-file 20",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                20 : { "name" : "Soldier, Rank-and-file 21",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                21 : { "name" : "Soldier, Rank-and-file 22",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                22 : { "name" : "Soldier, Rank-and-file 23",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                23 : { "name" : "Soldier, Rank-and-file 24",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                24 : { "name" : "Soldier, Rank-and-file 25",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                25 : { "name" : "Soldier, Rank-and-file 26",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                26 : { "name" : "Soldier, Rank-and-file 27",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                27 : { "name" : "Soldier, Rank-and-file 28",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                28 : { "name" : "Soldier, Rank-and-file 29",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                29 : { "name" : "Soldier, Rank-and-file 30",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                30 : { "name" : "Soldier, Rank-and-file 31",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                31 : { "name" : "Soldier, Rank-and-file 32",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                32 : { "name" : "Soldier, Rank-and-file 33",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                33 : { "name" : "Soldier, Rank-and-file 34",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                34 : { "name" : "Soldier, Rank-and-file 35",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                35 : { "name" : "Soldier, Rank-and-file 36",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                36 : { "name" : "Soldier, Rank-and-file 37",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                37 : { "name" : "Soldier, Rank-and-file 38",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                38 : { "name" : "Soldier, Rank-and-file 39",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                39 : { "name" : "Soldier, Rank-and-file 40",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                40 : { "name" : "Soldier, Rank-and-file 41",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                41 : { "name" : "Soldier, Rank-and-file 42",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]} ,

                42 : { "name" : "Soldier, Rank-and-file 43",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                43 : { "name" : "Soldier, Rank-and-file 44",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]} ,

                44 : { "name" : "Soldier, Rank-and-file 45",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                45 : { "name" : "Soldier, Rank-and-file 46",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]} ,

                46 : { "name" : "Soldier, Rank-and-file 47",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                47 : { "name" : "Soldier, Rank-and-file 48",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]}
                }

    #Loop until dead.
    Dead = False
    while Dead == False:

        #Get the player's next 'command'
        command = input("o==[=========>").lower().split()

        #If player dies, game ends.
        if Dead == True:
            print("You died!")
            break
