import random

HitZones = {
                1 : { "name" : "Lower Legs" }
             }

import MeleeWeapons           
Armors = {
    
                1 : { "name" : "Gambeson" ,
                      "description" : "Pliable textile armor made of a number of layers of quilted cloth and stuffed with cotton, animal hair, or other padding." ,
                      "pAV" : 1,
                      "bAV" : 2,
                      "cAV" : 2} ,

                2 : { "name" : "Leather" ,
                      "description" : "Tough, yet pliable, cured hide." ,
                      "pAV" : 2,
                      "bAV" : 1,
                      "cAV" : 2} ,

                3 : { "name" : "Leather with Metal" ,
                      "description" : "Pliable leather with short metal strips or rings sewn in strategic places to guard against cuts." ,
                      "pAV" : 2,
                      "bAV" : 1,
                      "cAV" : 3} ,

                4 : { "name" : "Hardened Leather" ,
                      "description" : "Cured hide boiled and then dried to make it harder, at the cost of pliability. It can be fashioned into segments large enough to serve as helmets and greaves, but not for workable breastplates." ,
                      "pAV" : 3,
                      "bAV" : 2,
                      "cAV" : 2} ,

                5 : { "name" : "Leather Lamellar" ,
                      "description" : "Strips of leather with holes fashioned into its edges and that are bound together and overlapped by neighboring pieces. Leather Lamellar is quite rigid and cannot be used to protect a joint. Requires wearing a gambeson underneath." ,
                      "pAV" : 3,
                      "bAV" : 3,
                      "cAV" : 3} ,

                6 : { "name" : "Metal Lamellar" ,
                      "description" : "Strips of metal with holes fashioned into its edges and that are bound together and overlapped by neighboring pieces. Leather Lamellar is quite rigid and cannot be used to protect a joint. Requires a gambeson to be worn underneath." ,
                      "pAV" : 4,
                      "bAV" : 4} ,

                7 : { "name" : "Brigandine" ,
                      "description" : "Armor made of palm- to hand-sized metal plates, each sandwiched between two layers of heavy canvas or soft leather and riveted together. Brigandine is quite rigit and cannot be used to protect joints, and requires a gambeson to be worn underneath." ,
                      "pAV" : 4,
                      "bAV" : 4} ,
                
                8 : { "name" : "Mail" ,
                      "description" : "This armor consists of a mesh of small metal rings, each interlinked with neighboring rings. It is supremely pliable and can therefore be used to protect joints, but it too requires a gambeson to be worn underneath" ,
                      "pAV" : 4,
                      "bAV" : 3} ,

                9 : { "name" : "Brigandine over Mail" ,
                      "description" : "" ,
                      "pAV" : 5,
                      "bAV" : 3} ,

                10 : { "name" : "Plate Pieces" ,
                       "description" : "" ,
                       "pAV" : 6,
                       "bAV" : 4} ,

                11 : { "name" : "Articulated Plate" ,
                       "description" : "" ,
                       "pAV" : 7,
                       "bAV" : 5}
                
           }

Shields = {
                1 : { "name" : "Buckler" ,
                      "description" : "" ,
                      "mDTN" : 7,
                      "tDTN" : 8,
                      "pDTN" : 11} ,

                2 : { "name" : "Small Shield" ,
                      "description" : "" ,
                      "mDTN" : 6,
                      "tDTN" : 7,
                      "pDTN" : 9} ,

                3 : { "name" : "Large Shield" ,
                      "description" : "" ,
                      "mDTN" : 5,
                      "tDTN" : 6,
                      "pDTN" : 7}
            }

#Decide what type of game you will be playing. For now there is just Gladiator
GameType = input("What type of game do you want to play? For now there is only Gladiator.\n>")
if GameType == "Gladiator":
    #Create a dictionary of rooms.
    Rooms = {
                1 : { "name" : "the Preparation Room"},

                2 : { "name" : "the Arena"}
              }
    #Set the player in the first room.
    currentRoom = 1
    print("You find yourself in the preparation room beneath the Arena. You hear the roar of the crowd above you.")
    print("o==[=========> <=========]==o")

    #Define Humanoids, the framework for both the player and most enemies.
    class Humanoid:
        def __init__(self, name, brawn, daring, tenacity, heart, sagacity, cunning, reflex, aim, knockdown, knockout, proficiency, weapon, shield, armor, zones):
            self.name = name
            self.brawn = brawn
            self.daring = daring
            self.tenacity = tenacity
            self.heart = heart
            self.sagacity = sagacity
            self.cunning = cunning
            self.reflex = reflex
            self.aim = aim
            self.knockdown = knockdown
            self.knockout = knockout
            self.proficiency = proficiency
            self.weapon = weapon
            self.shield = shield
            self.armor = armor
            self.zone1 = zones

    #Define and create a dictionary of Characters.
#    Character = {
#                0 : { "name" : "Gladiator",
#                      "brawn" : ,
#                      "daring" : ,
#                      "tenacity" : ,
#                      "heart" : ,
#                      "sagacity" : ,
#                      "cunning" : ,
#                      "proficiency" : ,
#                      "weapon" : MeleeWeapons[15],
#                      "shield" : Shields[1]} ,
#                }

    #Define and create a dictionary of Enemies.
    Enemies = {
                0 : { "name" : "Slave Fighter 1",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                1 : { "name" : "Slave Fighter 2",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : 2} ,

                2 : { "name" : "Slave Fighter 3",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                3 : { "name" : "Slave Fighter 4",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                4 : { "name" : "Soldier, Rank-and-file 5",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                5 : { "name" : "Soldier, Rank-and-file 6",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                6 : { "name" : "Soldier, Rank-and-file 7",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                7 : { "name" : "Soldier, Rank-and-file 8",
                      "brawn" : 4,
                      "daring" : 5,
                      "tenacity" : 4,
                      "heart" : 4,
                      "sagacity" : 3,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[14],
                      "shield" : Shields[2]} ,

                8 : { "name" : "Soldier, Rank-and-file 9",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 5,
                      "weapon" : MeleeWeapons[15],
                      "shield" : Shields[2]} ,

                9 : { "name" : "Soldier, Rank-and-file 10",
                      "brawn" : 5,
                      "daring" : 4,
                      "tenacity" : 4,
                      "heart" : 3,
                      "sagacity" : 4,
                      "cunning" : 4,
                      "proficiency" : 4,
                      "weapon" : MeleeWeapons[15],
                      "shield" : Shields[2]} ,

                10 : { "name" : "Soldier, Rank-and-file 11",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                11 : { "name" : "Soldier, Rank-and-file 12",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                12 : { "name" : "Soldier, Rank-and-file 13",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                13 : { "name" : "Soldier, Rank-and-file 14",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                14 : { "name" : "Soldier, Rank-and-file 15",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                15 : { "name" : "Soldier, Rank-and-file 16",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15],
                       "shield" : Shields[2]} ,

                16 : { "name" : "Soldier, Rank-and-file 17",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                17 : { "name" : "Soldier, Rank-and-file 18",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                18 : { "name" : "Soldier, Rank-and-file 19",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                19 : { "name" : "Soldier, Rank-and-file 20",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                20 : { "name" : "Soldier, Rank-and-file 21",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                21 : { "name" : "Soldier, Rank-and-file 22",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                22 : { "name" : "Soldier, Rank-and-file 23",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                23 : { "name" : "Soldier, Rank-and-file 24",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21],
                       "shield" : Shields[2]} ,

                24 : { "name" : "Soldier, Rank-and-file 25",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                25 : { "name" : "Soldier, Rank-and-file 26",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                26 : { "name" : "Soldier, Rank-and-file 27",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                27 : { "name" : "Soldier, Rank-and-file 28",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                28 : { "name" : "Soldier, Rank-and-file 29",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                29 : { "name" : "Soldier, Rank-and-file 30",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                30 : { "name" : "Soldier, Rank-and-file 31",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[14]} ,

                31 : { "name" : "Soldier, Rank-and-file 32",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[14]} ,

                32 : { "name" : "Soldier, Rank-and-file 33",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                33 : { "name" : "Soldier, Rank-and-file 34",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                34 : { "name" : "Soldier, Rank-and-file 35",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                35 : { "name" : "Soldier, Rank-and-file 36",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                36 : { "name" : "Soldier, Rank-and-file 37",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                37 : { "name" : "Soldier, Rank-and-file 38",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                38 : { "name" : "Soldier, Rank-and-file 39",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[15]} ,

                39 : { "name" : "Soldier, Rank-and-file 40",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[15]} ,

                40 : { "name" : "Soldier, Rank-and-file 41",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                41 : { "name" : "Soldier, Rank-and-file 42",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]} ,

                42 : { "name" : "Soldier, Rank-and-file 43",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                43 : { "name" : "Soldier, Rank-and-file 44",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]} ,

                44 : { "name" : "Soldier, Rank-and-file 45",
                       "brawn" : 5,
                       "daring" : 4,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                45 : { "name" : "Soldier, Rank-and-file 46",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]} ,

                46 : { "name" : "Soldier, Rank-and-file 47",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 3,
                       "sagacity" : 4,
                       "cunning" : 4,
                       "proficiency" : 4,
                       "weapon" : MeleeWeapons[21]} ,

                47 : { "name" : "Soldier, Rank-and-file 48",
                       "brawn" : 4,
                       "daring" : 5,
                       "tenacity" : 4,
                       "heart" : 4,
                       "sagacity" : 3,
                       "cunning" : 4,
                       "proficiency" : 5,
                       "weapon" : MeleeWeapons[21]}
                }

    #Loop until dead.
    Dead = False
    while Dead == False:

        #Get the player's next 'command'
        command = input("o==[=========>").lower().split()

        #If player dies, game ends.
        if Dead == True:
            print("You died!")
            break
